// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PicturesColumns holds the columns for the "pictures" table.
	PicturesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "filename", Type: field.TypeString, Unique: true},
		{Name: "original_filename", Type: field.TypeString},
		{Name: "dir", Type: field.TypeString},
		{Name: "digest", Type: field.TypeString},
		{Name: "is_upscaled", Type: field.TypeBool, Default: false},
		{Name: "original_width", Type: field.TypeInt},
		{Name: "original_height", Type: field.TypeInt},
		{Name: "upscaled_width", Type: field.TypeInt, Default: 0},
		{Name: "upscaled_height", Type: field.TypeInt, Default: 0},
		{Name: "upscale_ratio", Type: field.TypeInt, Default: 1},
		{Name: "error_message", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"unknown", "processing", "done", "error"}, Default: "unknown"},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PicturesTable holds the schema information for the "pictures" table.
	PicturesTable = &schema.Table{
		Name:       "pictures",
		Columns:    PicturesColumns,
		PrimaryKey: []*schema.Column{PicturesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "picture_original_filename",
				Unique:  false,
				Columns: []*schema.Column{PicturesColumns[2]},
			},
			{
				Name:    "picture_digest",
				Unique:  false,
				Columns: []*schema.Column{PicturesColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PicturesTable,
	}
)

func init() {
}
